<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ImageSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('images')->insert([
            ['product_id' => 	1	, 'color_id' =>	1	, 'src' =>	'MODENA_2,5_SEATER1.jpg#MODENA_2,5_SEATER2.jpg#MODENA_2,5_SEATER3.jpg#MODENA_2,5_SEATER4.jpg'	],
            ['product_id' => 	1	, 'color_id' =>	4	, 'src' =>	'MODENA_2,5_SEATER1B.jpg#MODENA_2,5_SEATER2B.jpg#MODENA_2,5_SEATER3B.jpg#MODENA_2,5_SEATER4B.jpg'	],
            ['product_id' => 	1	, 'color_id' =>	3	, 'src' =>	'MODENA_2,5_SEATER1G.jpg#MODENA_2,5_SEATER2G.jpg#MODENA_2,5_SEATER3G.jpg#MODENA_2,5_SEATER4G.jpg'	],
            ['product_id' => 	2	, 'color_id' =>	6	, 'src' =>	'HAMPTON_CORNER_SOFA_1.jpg#HAMPTON_CORNER_SOFA2.jpg#HAMPTON_CORNER_SOFA_3.jpg#HAMPTON_CORNER_SOFA_4.jpg'	],
            ['product_id' => 	2	, 'color_id' =>	3	, 'src' =>	'HAMPTON_CORNER_SOFA_1G.jpg#HAMPTON_CORNER_SOFA_2G.jpg#HAMPTON_CORNER_SOFA_3G.jpg#HAMPTON_CORNER_SOFA_4G.jpg'	],
            ['product_id' => 	3	, 'color_id' =>	6	, 'src' =>	'AMSTERDAM_RESTING_MODULE_1.jpg#AMSTERDAM_RESTING_MODULE_2.jpg#AMSTERDAM_RESTING_MODULE_3.jpg#AMSTERDAM_RESTING_MODULE_4.jpg'	],
            ['product_id' => 	3	, 'color_id' =>	5	, 'src' =>	'AMSTERDAM_RESTING_MODULE_1BR.jpg#AMSTERDAM_RESTING_MODULE_2BR.jpg#AMSTERDAM_RESTING_MODULE_3BR.jpg#AMSTERDAM_RESTING_MODULE_4BR.jpg'	],
            ['product_id' => 	3	, 'color_id' =>	3	, 'src' =>	'AMSTERDAM_RESTING_MODULE_1G.jpg#AMSTERDAM_RESTING_MODULE_2G.jpg#AMSTERDAM_RESTING_MODULE_3G.jpg#AMSTERDAM_RESTING_MODULE_4G.jpg'	],
            ['product_id' => 	4	, 'color_id' =>	6	, 'src' =>	'AMSTERDAM_2,5_SEATING1.jpg#AMSTERDAM_2,5_SEATING2.jpg#AMSTERDAM_2,5_SEATING3.jpg#AMSTERDAM_2,5_SEATING4.jpg'	],
            ['product_id' => 	4	, 'color_id' =>	5	, 'src' =>	'AMSTERDAM_2,5_SEATING1BR.jpg#AMSTERDAM_2,5_SEATING2BR.jpg#AMSTERDAM_2,5_SEATING3BR.jpg#AMSTERDAM_2,5_SEATING4BR.jpg'	],
            ['product_id' => 	4	, 'color_id' =>	2	, 'src' =>	'AMSTERDAM_2,5_SEATING1BE.jpg#AMSTERDAM_2,5_SEATING2BE.jpg#AMSTERDAM_2,5_SEATING3BE.jpg#AMSTERDAM_2,5_SEATING4BE.jpg'	],
            ['product_id' => 	5	, 'color_id' =>	3	, 'src' =>	'LILLE_2,5_SEATER_WITH_ARMRESTS_1.jpg#LILLE_2,5_SEATER_WITH_ARMRESTS_2.jpg#LILLE_2,5_SEATER_WITH_ARMRESTS_3.jpg#LILLE_2,5_SEATER_WITH_ARMRESTS_4.jpg'	],
            ['product_id' => 	5	, 'color_id' =>	4	, 'src' =>	'LILLE_2,5_SEATER_WITH_ARMRESTS_1B.jpg#LILLE_2,5_SEATER_WITH_ARMRESTS_2B.jpg#LILLE_2,5_SEATER_WITH_ARMRESTS_3B.jpg#LILLE_2,5_SEATER_WITH_ARMRESTS_4B.jpg'	],
            ['product_id' => 	5	, 'color_id' =>	5	, 'src' =>	'LILLE_2,5_SEATER_WITH_ARMRESTS_1BR.jpg#LILLE_2,5_SEATER_WITH_ARMRESTS_2BR.jpg#LILLE_2,5_SEATER_WITH_ARMRESTS_3BR.jpg#LILLE_2,5_SEATER_WITH_ARMRESTS_4BR.jpg'	],
            ['product_id' => 	6	, 'color_id' =>	1	, 'src' =>	'ZURICH_SOFA_WITH_RESTING_UNIT1.jpg#ZURICH_SOFA_WITH_RESTING_UNIT2.jpg#ZURICH_SOFA_WITH_RESTING_UNIT3.jpg#ZURICH_SOFA_WITH_RESTING_UNIT4.jpg'	],
            ['product_id' => 	6	, 'color_id' =>	2	, 'src' =>	'ZURICH_SOFA_WITH_RESTING_UNIT_1BE.jpg#ZURICH_SOFA_WITH_RESTING_UNIT_2BE.jpg#ZURICH_SOFA_WITH_RESTING_UNIT_3BE.jpg#ZURICH_SOFA_WITH_RESTING_UNIT_4BE.jpg'	],
            ['product_id' => 	6	, 'color_id' =>	5	, 'src' =>	'ZURICH_SOFA_WITH_RESTING_UNIT_1BR.jpg#ZURICH_SOFA_WITH_RESTING_UNIT_2BR.jpg#ZURICH_SOFA_WITH_RESTING_UNIT_3BR.jpg#ZURICH_SOFA_WITH_RESTING_UNIT_4BR.jpg'	],
            ['product_id' => 	7	, 'color_id' =>	6	, 'src' =>	'FARGO_SOFA1.jpg#FARGO_SOFA2.jpg#FARGO_SOFA3.jpg#FARGO_SOFA4.jpg'	],
            ['product_id' => 	7	, 'color_id' =>	1	, 'src' =>	'FARGO_SOFA_1W.jpg#FARGO_SOFA_2W.jpg#FARGO_SOFA_3W.jpg#FARGO_SOFA_4W.jpg'	],
            ['product_id' => 	7	, 'color_id' =>	4	, 'src' =>	'FARGO_SOFA_1B.jpg#FARGO_SOFA_2B.jpg#FARGO_SOFA_3B.jpg#FARGO_SOFA_B.jpg'	],
            ['product_id' => 	8	, 'color_id' =>	4	, 'src' =>	'OTTAWA_SOFA1.jpg#OTTAWA_SOFA2.jpg#OTTAWA_SOFA3.jpg#OTTAWA_SOFA4.jpg'	],
            ['product_id' => 	8	, 'color_id' =>	2	, 'src' =>	'OTTAWA_SOFA_1BE.jpg#OTTAWA_SOFA_2BE.jpg#OTTAWA_SOFA_3BE.jpg#OTTAWA_SOFA_4BE.jpg'	],
            ['product_id' => 	8	, 'color_id' =>	3	, 'src' =>	'OTTAWA_SOFA_1G.jpg#OTTAWA_SOFA_2G.jpg#OTTAWA_SOFA_3G.jpg#OTTAWA_SOFA_4G.jpg'	],
            ['product_id' => 	9	, 'color_id' =>	4	, 'src' =>	'HAMPTON_SOFA_WITH_ADJUSTABLE_BACK_AND_STORAGE_ON_THE_RIGHT_SIDE1.jpg#HAMPTON_SOFA_WITH_ADJUSTABLE_BACK_AND_STORAGE_ON_THE_RIGHT_SIDE2.jpg#HAMPTON_SOFA_WITH_ADJUSTABLE_BACK_AND_STORAGE_ON_THE_RIGHT_SIDE3.jpg#HAMPTON_SOFA_WITH_ADJUSTABLE_BACK_AND_STORAGE_ON_THE_RIGHT_SIDE4.jpg'	],
            ['product_id' => 	9	, 'color_id' =>	2	, 'src' =>	'HAMPTON_SOFA_WITH_ADJUSTABLE_BACK_AND_STORAGE_ON_THE_RIGHT_SIDE_1BE.jpg#HAMPTON_SOFA_WITH_ADJUSTABLE_BACK_AND_STORAGE_ON_THE_RIGHT_SIDE_2BE.jpg#HAMPTON_SOFA_WITH_ADJUSTABLE_BACK_AND_STORAGE_ON_THE_RIGHT_SIDE_3BE.jpg#HAMPTON_SOFA_WITH_ADJUSTABLE_BACK_AND_STORAGE_ON_THE_RIGHT_SIDE_4BE.jpg'	],
            ['product_id' => 	9	, 'color_id' =>	3	, 'src' =>	'HAMPTON_SOFA_WITH_ADJUSTABLE_BACK_AND_STORAGE_ON_THE_RIGHT_SIDE_1G.jpg#HAMPTON_SOFA_WITH_ADJUSTABLE_BACK_AND_STORAGE_ON_THE_RIGHT_SIDE_2G.jpg#HAMPTON_SOFA_WITH_ADJUSTABLE_BACK_AND_STORAGE_ON_THE_RIGHT_SIDE_3G.jpg#HAMPTON_SOFA_WITH_ADJUSTABLE_BACK_AND_STORAGE_ON_THE_RIGHT_SIDE_4G.jpg'	],
            ['product_id' => 	10	, 'color_id' =>	1	, 'src' =>	'CARMO_SOFA_WITH_LOUNGING_AND_RESTING_UNIT1.jpg#CARMO_SOFA_WITH_LOUNGING_AND_RESTING_UNIT2.jpg#CARMO_SOFA_WITH_LOUNGING_AND_RESTING_UNIT3.jpg#CARMO_SOFA_WITH_LOUNGING_AND_RESTING_UNIT4.jpg'	],
            ['product_id' => 	10	, 'color_id' =>	5	, 'src' =>	'CARMO_SOFA_WITH_LOUNGING_AND_RESTING_UNIT_1BR.jpg#CARMO_SOFA_WITH_LOUNGING_AND_RESTING_UNIT_2BR.jpg#CARMO_SOFA_WITH_LOUNGING_AND_RESTING_UNIT_3BR.jpg#CARMO_SOFA_WITH_LOUNGING_AND_RESTING_UNIT_4BR.jpg'	],
            ['product_id' => 	10	, 'color_id' =>	3	, 'src' =>	'CARMO_SOFA_WITH_LOUNGING_AND_RESTING_UNIT_1G.jpg#CARMO_SOFA_WITH_LOUNGING_AND_RESTING_UNIT_2G.jpg#CARMO_SOFA_WITH_LOUNGING_AND_RESTING_UNIT_3G.jpg#CARMO_SOFA_WITH_LOUNGING_AND_RESTING_UNIT_4G.jpg'	],
            ['product_id' => 	11	, 'color_id' =>	2	, 'src' =>	'MODENA_CHAIR1.jpg#MODENA_CHAIR2.jpg#MODENA_CHAIR3.jpg#MODENA_CHAIR4.jpg'	],
            ['product_id' => 	12	, 'color_id' =>	2	, 'src' =>	'CHELSEA_CHAIR1.jpg#CHELSEA_CHAIR2.jpg#CHELSEA_CHAIR3.jpg#CHELSEA_CHAIR4.jpg'	],
            ['product_id' => 	13	, 'color_id' =>	3	, 'src' =>	'CARMO_CHAIR1.jpg#CARMO_CHAIR2.jpg#CARMO_CHAIR3.jpg#CARMO_CHAIR4.jpg'	],
            ['product_id' => 	14	, 'color_id' =>	2	, 'src' =>	'FUSION_CHAIR1.jpg#FUSION_CHAIR2.jpg#FUSION_CHAIR3.jpg#FUSION_CHAIR4.jpg'	],
            ['product_id' => 	15	, 'color_id' =>	1	, 'src' =>	'FLY_CHAIR1.jpg#FLY_CHAIR2.jpg#FLY_CHAIR3.jpg#FLY_CHAIR4.jpg'	],
            ['product_id' => 	16	, 'color_id' =>	4	, 'src' =>	'OSAKA_CHAIR1.jpg#OSAKA_CHAIR2.jpg#OSAKA_CHAIR3.jpg#OSAKA_CHAIR4.jpg'	],
            ['product_id' => 	17	, 'color_id' =>	2	, 'src' =>	'VENETO_CHAIR_WITH_SWIVEL_FUNCTION1.jpg#VENETO_CHAIR_WITH_SWIVEL_FUNCTION2.jpg#VENETO_CHAIR_WITH_SWIVEL_FUNCTION3.jpg#VENETO_CHAIR_WITH_SWIVEL_FUNCTION4.jpg'	],
            ['product_id' => 	18	, 'color_id' =>	6	, 'src' =>	'IMOLA_CHAIR1.jpg#IMOLA_CHAIR2.jpg#IMOLA_CHAIR3.jpg#IMOLA_CHAIR4.jpg'	],
            ['product_id' => 	19	, 'color_id' =>	2	, 'src' =>	'DUBLIN_CHAIR1.jpg#DUBLIN_CHAIR3.jpg#DUBLIN_CHAIR3.jpg#DUBLIN_CHAIR4.jpg'	],
            ['product_id' => 	20	, 'color_id' =>	6	, 'src' =>	'ATHENA_CHAIR_WITH_RECLINING_BACK_FUNCTION1.jpg#ATHENA_CHAIR_WITH_RECLINING_BACK_FUNCTION2.jpg#ATHENA_CHAIR_WITH_RECLINING_BACK_FUNCTION3.jpg#ATHENA_CHAIR_WITH_RECLINING_BACK_FUNCTION4.jpg'	],
            ['product_id' => 	21	, 'color_id' =>	1	, 'src' =>	'PRINCETON_CHAIR1.jpg#PRINCETON_CHAIR2.jpg#PRINCETON_CHAIR3.jpg#PRINCETON_CHAIR4.jpg'	],
            ['product_id' => 	22	, 'color_id' =>	5	, 'src' =>	'NEWPORT_CHAIR1.jpg#NEWPORT_CHAIR2.jpg#NEWPORT_CHAIR3.jpg#NEWPORT_CHAIR4.jpg'	],
            ['product_id' => 	23	, 'color_id' =>	1	, 'src' =>	'OTTAWA_CHAIR1.jpg#OTTAWA_CHAIR2.jpg#OTTAWA_CHAIR3.jpg#OTTAWA_CHAIR4.jpg'	],
            ['product_id' => 	24	, 'color_id' =>	3	, 'src' =>	'ADELAIDE_BARSTOOL1.jpg#ADELAIDE_BARSTOOL2.jpg#ADELAIDE_BARSTOOL3.jpg#ADELAIDE_BARSTOOL4.jpg'	],
            ['product_id' => 	25	, 'color_id' =>	6	, 'src' =>	'ELBA_CHAIR1.jpg#ELBA_CHAIR2.jpg#ELBA_CHAIR3.jpg#ELBA_CHAIR4.jpg'	],
            ['product_id' => 	26	, 'color_id' =>	2	, 'src' =>	'LAUSANNE_CHAIR1.jpg#LAUSANNE_CHAIR2.jpg#LAUSANNE_CHAIR3.jpg#LAUSANNE_CHAIR4.jpg'	],
            ['product_id' => 	27	, 'color_id' =>	5	, 'src' =>	'ADELAIDE_CHAIR_WITH_SWIVEL_FUNCTION1.jpg#ADELAIDE_CHAIR_WITH_SWIVEL_FUNCTION2.jpg#ADELAIDE_CHAIR_WITH_SWIVEL_FUNCTION3.jpg#ADELAIDE_CHAIR_WITH_SWIVEL_FUNCTION4.jpg'	],
            ['product_id' => 	28	, 'color_id' =>	1	, 'src' =>	'ADELAIDE_CHAIR1.jpg#ADELAIDE_CHAIR2.jpg#ADELAIDE_CHAIR3.jpg#ADELAIDE_CHAIR4.jpg'	],
            ['product_id' => 	29	, 'color_id' =>	4	, 'src' =>	'ADELAIDE_CHAIR_WITH_SWIVEL_FUNCTION_AND_WHEELS1.jpg#ADELAIDE_CHAIR_WITH_SWIVEL_FUNCTION_AND_WHEELS2.jpg#ADELAIDE_CHAIR_WITH_SWIVEL_FUNCTION_AND_WHEELS3.jpg#ADELAIDE_CHAIR_WITH_SWIVEL_FUNCTION_AND_WHEELS4.jpg'	],
            ['product_id' => 	30	, 'color_id' =>	3	, 'src' =>	'BOSTON_CHAIR_WITH_SWIVEL_FUNCTION1.jpg#BOSTON_CHAIR_WITH_SWIVEL_FUNCTION2.jpg#BOSTON_CHAIR_WITH_SWIVEL_FUNCTION3.jpg#BOSTON_CHAIR_WITH_SWIVEL_FUNCTION4.jpg'	],
            ['product_id' => 	31	, 'color_id' =>	1	, 'src' =>	'ALICANTE_TABLE_WITH_SUPPLEMENTARY_TABLETOP1.jpg#ALICANTE_TABLE_WITH_SUPPLEMENTARY_TABLETOP2.jpg#ALICANTE_TABLE_WITH_SUPPLEMENTARY_TABLETOP3.jpg#ALICANTE_TABLE_WITH_SUPPLEMENTARY_TABLETOP4.jpg'	],
            ['product_id' => 	32	, 'color_id' =>	1	, 'src' =>	'MADRID_COFFEE_TABLE1.jpg#MADRID_COFFEE_TABLE2.jpg#MADRID_COFFEE_TABLE3.jpg#MADRID_COFFEE_TABLE4.jpg'	],
            ['product_id' => 	33	, 'color_id' =>	5	, 'src' =>	'CUPERTINO_DESK1.jpg#CUPERTINO_DESK2.jpg#CUPERTINO_DESK3.jpg#CUPERTINO_DESK4.jpg'	],
            ['product_id' => 	34	, 'color_id' =>	2	, 'src' =>	'CHIVA_FUNCTIONAL_COFFEE_TABLE_WITH_STORAGE1.jpg#CHIVA_FUNCTIONAL_COFFEE_TABLE_WITH_STORAGE2.jpg#CHIVA_FUNCTIONAL_COFFEE_TABLE_WITH_STORAGE3.jpg#CHIVA_FUNCTIONAL_COFFEE_TABLE_WITH_STORAGE4.jpg'	],
            ['product_id' => 	35	, 'color_id' =>	6	, 'src' =>	'PARIS_SIDE_TABLE1.jpg#PARIS_SIDE_TABLE2.jpg#PARIS_SIDE_TABLE3.jpg#PARIS_SIDE_TABLE4.jpg'	],
            ['product_id' => 	36	, 'color_id' =>	6	, 'src' =>	'EXPOSE_SIDE_TABLE1.jpg#EXPOSE_SIDE_TABLE2.jpg#EXPOSE_SIDE_TABLE3.jpg#EXPOSE_SIDE_TABLE4.jpg'	],
            ['product_id' => 	37	, 'color_id' =>	5	, 'src' =>	'RUBI_ADJUSTABLE_TABLE1.jpg#RUBI_ADJUSTABLE_TABLE2.jpg#RUBI_ADJUSTABLE_TABLE3.jpg#RUBI_ADJUSTABLE_TABLE4.jpg'	],
            ['product_id' => 	38	, 'color_id' =>	1	, 'src' =>	'ELBA_TABLE1.jpg#ELBA_TABLE2.jpg#ELBA_TABLE3.jpg#ELBA_TABLE4.jpg'	],
            ['product_id' => 	39	, 'color_id' =>	6	, 'src' =>	'PHOENIX_ELECTRIC_OFFICE_DESK1.jpg#PHOENIX_ELECTRIC_OFFICE_DESK2.jpg#PHOENIX_ELECTRIC_OFFICE_DESK3.jpg#PHOENIX_ELECTRIC_OFFICE_DESK4.jpg'	],
            ['product_id' => 	40	, 'color_id' =>	1	, 'src' =>	'BILLUND_TABLE1.jpg#BILLUND_TABLE2.jpg#BILLUND_TABLE3.jpg#BILLUND_TABLE4.jpg'	],
            ['product_id' => 	41	, 'color_id' =>	1	, 'src' =>	'FERMO_SIDEBOARD_LARGE1.jpg#FERMO_SIDEBOARD_LARGE2.jpg#FERMO_SIDEBOARD_LARGE3.jpg#FERMO_SIDEBOARD_LARGE4.jpg'	],
            ['product_id' => 	42	, 'color_id' =>	6	, 'src' =>	'COPENHAGEN_OFFICE_SYSTEM1.jpg#COPENHAGEN_OFFICE_SYSTEM2.jpg#COPENHAGEN_OFFICE_SYSTEM3.jpg#COPENHAGEN_OFFICE_SYSTEM4.jpg'	],
            ['product_id' => 	43	, 'color_id' =>	3	, 'src' =>	'COPENHAGEN_WALL_SYSTEM1.jpg#COPENHAGEN_WALL_SYSTEM2.jpg#COPENHAGEN_WALL_SYSTEM3.jpg#COPENHAGEN_WALL_SYSTEM4.jpg'	],
            ['product_id' => 	44	, 'color_id' =>	2	, 'src' =>	'COMO_BOOKCASE1.jpg#COMO_BOOKCASE2.jpg#COMO_BOOKCASE3.jpg#COMO_BOOKCASE4.jpg'	],
            ['product_id' => 	45	, 'color_id' =>	2	, 'src' =>	'BORDEAUX_CONSOLE_TABLE1.jpg#BORDEAUX_CONSOLE_TABLE2.jpg#BORDEAUX_CONSOLE_TABLE3.jpg#BORDEAUX_CONSOLE_TABLE4.jpg'	],
            ['product_id' => 	46	, 'color_id' =>	5	, 'src' =>	'ATLANTA_BASE_CABINET_WITH_DRAWERS_AND_BOOKCASE1.jpg#ATLANTA_BASE_CABINET_WITH_DRAWERS_AND_BOOKCASE2.jpg#ATLANTA_BASE_CABINET_WITH_DRAWERS_AND_BOOKCASE3.jpg#ATLANTA_BASE_CABINET_WITH_DRAWERS_AND_BOOKCASE4.jpg'	],
            ['product_id' => 	47	, 'color_id' =>	1	, 'src' =>	'OTTAWA_SIDEBOARD1.jpg#OTTAWA_SIDEBOARD2.jpg#OTTAWA_SIDEBOARD3.jpg#OTTAWA_SIDEBOARD4.jpg'	],
            ['product_id' => 	48	, 'color_id' =>	2	, 'src' =>	'COPENHAGEN_WALL1.jpg#COPENHAGEN_WALL2.jpg#COPENHAGEN_WALL3.jpg#COPENHAGEN_WALL4.jpg'	],
            ['product_id' => 	49	, 'color_id' =>	5	, 'src' =>	'ATLANTA_BASE_CABINET_WITH_DOORS_AND_BOOKCASE1.jpg#ATLANTA_BASE_CABINET_WITH_DOORS_AND_BOOKCASE2.jpg#ATLANTA_BASE_CABINET_WITH_DOORS_AND_BOOKCASE3.jpg#ATLANTA_BASE_CABINET_WITH_DOORS_AND_BOOKCASE4.jpg'	],
            ['product_id' => 	50	, 'color_id' =>	6	, 'src' =>	'BORDEAUX_WALL1.jpg#BORDEAUX_WALL2.jpg#BORDEAUX_WALL3.jpg#BORDEAUX_WALL4.jpg'	],
            ['product_id' => 	51	, 'color_id' =>	2	, 'src' =>	'AUSTIN_BED_EXCL_MATTRESS1.jpg#AUSTIN_BED_EXCL_MATTRESS2.jpg#AUSTIN_BED_EXCL_MATTRESS3.jpg#AUSTIN_BED_EXCL_MATTRESS4.jpg'	],
            ['product_id' => 	52	, 'color_id' =>	4	, 'src' =>	'ARLINGTON_BED_EXCL_MATTRESS1.jpg#ARLINGTON_BED_EXCL_MATTRESS2.jpg#ARLINGTON_BED_EXCL_MATTRESS3.jpg#ARLINGTON_BED_EXCL_MATTRESS4.jpg'	],
            ['product_id' => 	53	, 'color_id' =>	2	, 'src' =>	'HOUSTON_UPHOLSTERED_BED_WITH_STORAGE1.jpg#HOUSTON_UPHOLSTERED_BED_WITH_STORAGE2.jpg#HOUSTON_UPHOLSTERED_BED_WITH_STORAGE3.jpg#HOUSTON_UPHOLSTERED_BED_WITH_STORAGE4.jpg'	],
            ['product_id' => 	54	, 'color_id' =>	3	, 'src' =>	'LUGANO_STORAGE_BED_WITH_LIFT-UP_FRAME_AND_SLATS1.jpg#LUGANO_STORAGE_BED_WITH_LIFT-UP_FRAME_AND_SLATS2.jpg#LUGANO_STORAGE_BED_WITH_LIFT-UP_FRAME_AND_SLATS3.jpg#LUGANO_STORAGE_BED_WITH_LIFT-UP_FRAME_AND_SLATS4.jpg'	],
            ['product_id' => 	55	, 'color_id' =>	2	, 'src' =>	'MEZZO_BED_EXCL_MATTRESS1.jpg#MEZZO_BED_EXCL_MATTRESS2.jpg#MEZZO_BED_EXCL_MATTRESS3.jpg#MEZZO_BED_EXCL_MATTRESS4.jpg'	],
            ['product_id' => 	56	, 'color_id' =>	1	, 'src' =>	'LUGANO_BED_EXCL_MATTRESS1.jpg#LUGANO_BED_EXCL_MATTRESS2.jpg#LUGANO_BED_EXCL_MATTRESS3.jpg#LUGANO_BED_EXCL_MATTRESS4.jpg'	],
            ['product_id' => 	57	, 'color_id' =>	1	, 'src' =>	'LUGANO_WITHOUT_HEADBOARD_WITH_SLATS_AND_LEGS1.jpg#LUGANO_WITHOUT_HEADBOARD_WITH_SLATS_AND_LEGS2.jpg#LUGANO_WITHOUT_HEADBOARD_WITH_SLATS_AND_LEGS3.jpg#LUGANO_WITHOUT_HEADBOARD_WITH_SLATS_AND_LEGS4.jpg'	],
            ['product_id' => 	58	, 'color_id' =>	2	, 'src' =>	'LUGANO_STORAGE_BED_WITH_LIFTUP_FRAME_AND_SLATS_EXCL_MATTRESS1.jpg#LUGANO_STORAGE_BED_WITH_LIFTUP_FRAME_AND_SLATS_EXCL_MATTRESS2.jpg#LUGANO_STORAGE_BED_WITH_LIFTUP_FRAME_AND_SLATS_EXCL_MATTRESS3.jpg#LUGANO_STORAGE_BED_WITH_LIFTUP_FRAME_AND_SLATS_EXCL_MATTRESS4.jpg'	],
            ['product_id' => 	59	, 'color_id' =>	3	, 'src' =>	'HOUSTON_BED_EXCL_MATTRESS1.jpg#HOUSTON_BED_EXCL_MATTRESS2.jpg#HOUSTON_BED_EXCL_MATTRESS3.jpg#HOUSTON_BED_EXCL_MATTRESS4.jpg'	],
            ['product_id' => 	60	, 'color_id' =>	3	, 'src' =>	'MEZZO_STORAGE_BED_WITH_LIFTUP_FRAME_AND_SLATS_EXCL_MATTRESS1.jpg#MEZZO_STORAGE_BED_WITH_LIFTUP_FRAME_AND_SLATS_EXCL_MATTRESS2.jpg#MEZZO_STORAGE_BED_WITH_LIFTUP_FRAME_AND_SLATS_EXCL_MATTRESS3.jpg#MEZZO_STORAGE_BED_WITH_LIFTUP_FRAME_AND_SLATS_EXCL_MATTRESS4.jpg'	],
            ['product_id' => 	61	, 'color_id' =>	3	, 'src' =>	'KUTA_FLOOR_LAMP1.jpg#KUTA_FLOOR_LAMP2.jpg#KUTA_FLOOR_LAMP3.jpg#KUTA_FLOOR_LAMP4.jpg'	],
            ['product_id' => 	62	, 'color_id' =>	5	, 'src' =>	'PINE_CONE_PENDANT1.jpg#PINE_CONE_PENDANT2.jpg#PINE_CONE_PENDANT3.jpg#PINE_CONE_PENDANT4.jpg'	],
            ['product_id' => 	63	, 'color_id' =>	1	, 'src' =>	'DAWN_TABLE_LAMP1.jpg#DAWN_TABLE_LAMP2.jpg#DAWN_TABLE_LAMP3.jpg#DAWN_TABLE_LAMP4.jpg'	],
            ['product_id' => 	64	, 'color_id' =>	6	, 'src' =>	'QUADRO_WALL_LAMP1.jpg#QUADRO_WALL_LAMP2.jpg#QUADRO_WALL_LAMP3.jpg#QUADRO_WALL_LAMP4.jpg'	],
            ['product_id' => 	65	, 'color_id' =>	3	, 'src' =>	'SHELTER_TABLE_LAMP1.jpg#SHELTER_TABLE_LAMP2.jpg#SHELTER_TABLE_LAMP3.jpg#SHELTER_TABLE_LAMP4.jpg'	],
            ['product_id' => 	66	, 'color_id' =>	6	, 'src' =>	'LEVEL_PENDANT1.jpg#LEVEL_PENDANT2.jpg#LEVEL_PENDANT3.jpg#LEVEL_PENDANT4.jpg'	],
            ['product_id' => 	67	, 'color_id' =>	5	, 'src' =>	'FIVE_CHANDELIER1.jpg#FIVE_CHANDELIER2.jpg#FIVE_CHANDELIER3.jpg#FIVE_CHANDELIER4.jpg'	],
            ['product_id' => 	68	, 'color_id' =>	6	, 'src' =>	'CURIOUS_FLOOR_LAMP1.jpg#CURIOUS_FLOOR_LAMP2.jpg#CURIOUS_FLOOR_LAMP3.jpg#CURIOUS_FLOOR_LAMP4.jpg'	],
            ['product_id' => 	69	, 'color_id' =>	6	, 'src' =>	'DEMAND_TABLE_LAMP1.jpg#DEMAND_TABLE_LAMP2.jpg#DEMAND_TABLE_LAMP3.jpg#DEMAND_TABLE_LAMP4.jpg'	],
            ['product_id' => 	70	, 'color_id' =>	5	, 'src' =>	'STOCKHOLM_TABLE_LAMP1.jpg#STOCKHOLM_TABLE_LAMP2.jpg#STOCKHOLM_TABLE_LAMP3.jpg#STOCKHOLM_TABLE_LAMP4.jpg'	],                 
        ]);
    }
}
