<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ImageSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('images')->insert([
            ['product_id' =>	1	, 'color_id' =>	1	, 'src' =>	'MODENA 2,5 SEATER1.jpg#MODENA 2,5 SEATER2.jpg#MODENA 2,5 SEATER3.jpg#MODENA 2,5 SEATER4.jpg'	],
            ['product_id' =>	1	, 'color_id' =>	4	, 'src' =>	'MODENA 2,5 SEATER1B.jpg#MODENA 2,5 SEATER2B.jpg#MODENA 2,5 SEATER3B.jpg#MODENA 2,5 SEATER4B.jpg'	],
            ['product_id' =>	1	, 'color_id' =>	3	, 'src' =>	'MODENA 2,5 SEATER1G.jpg#MODENA 2,5 SEATER2G.jpg#MODENA 2,5 SEATER3G.jpg#MODENA 2,5 SEATER4G.jpg'	],
            ['product_id' =>	2	, 'color_id' =>	6	, 'src' =>	'HAMPTON CORNER SOFA 1.jpg#HAMPTON CORNER SOFA2.jpg#HAMPTON CORNER SOFA 3.jpg#HAMPTON CORNER SOFA 4.jpg'	],
            ['product_id' =>	2	, 'color_id' =>	3	, 'src' =>	'HAMPTON CORNER SOFA 1G.jpg#HAMPTON CORNER SOFA 2G.jpg#HAMPTON CORNER SOFA 3G.jpg#HAMPTON CORNER SOFA 4G.jpg'	],
            ['product_id' =>	3	, 'color_id' =>	6	, 'src' =>	'AMSTERDAM RESTING MODULE 1.jpg#AMSTERDAM RESTING MODULE 2.jpg#AMSTERDAM RESTING MODULE 3.jpg#AMSTERDAM RESTING MODULE 4.jpg'	],
            ['product_id' =>	3	, 'color_id' =>	5	, 'src' =>	'AMSTERDAM RESTING MODULE 1BR.jpg#AMSTERDAM RESTING MODULE 2BR.jpg#AMSTERDAM RESTING MODULE 3BR.jpg#AMSTERDAM RESTING MODULE 4BR.jpg'	],
            ['product_id' =>	3	, 'color_id' =>	3	, 'src' =>	'AMSTERDAM RESTING MODULE 1G.jpg#AMSTERDAM RESTING MODULE 2G.jpg#AMSTERDAM RESTING MODULE 3G.jpg#AMSTERDAM RESTING MODULE 4G.jpg'	],
            ['product_id' =>	4	, 'color_id' =>	6	, 'src' =>	'AMSTERDAM 2,5 SEATING1.jpg#AMSTERDAM 2,5 SEATING2.jpg#AMSTERDAM 2,5 SEATING3.jpg#AMSTERDAM 2,5 SEATING4.jpg'	],
            ['product_id' =>	4	, 'color_id' =>	5	, 'src' =>	'AMSTERDAM 2,5 SEATING1BR.jpg#AMSTERDAM 2,5 SEATING2BR.jpg#AMSTERDAM 2,5 SEATING3BR.jpg#AMSTERDAM 2,5 SEATING4BR.jpg'	],
            ['product_id' =>	4	, 'color_id' =>	2	, 'src' =>	'AMSTERDAM 2,5 SEATING1BE.jpg#AMSTERDAM 2,5 SEATING2BE.jpg#AMSTERDAM 2,5 SEATING3BE.jpg#AMSTERDAM 2,5 SEATING4BE.jpg'	],
            ['product_id' =>	5	, 'color_id' =>	3	, 'src' =>	'LILLE 2,5 SEATER WITH ARMRESTS 1.jpg#LILLE 2,5 SEATER WITH ARMRESTS 2.jpg#LILLE 2,5 SEATER WITH ARMRESTS 3.jpg#LILLE 2,5 SEATER WITH ARMRESTS 4.jpg'	],
            ['product_id' =>	5	, 'color_id' =>	4	, 'src' =>	'LILLE 2,5 SEATER WITH ARMRESTS 1B.jpg#LILLE 2,5 SEATER WITH ARMRESTS 2B.jpg#LILLE 2,5 SEATER WITH ARMRESTS 3B.jpg#LILLE 2,5 SEATER WITH ARMRESTS 4B.jpg'	],
            ['product_id' =>	5	, 'color_id' =>	5	, 'src' =>	'LILLE 2,5 SEATER WITH ARMRESTS 1BR.jpg#LILLE 2,5 SEATER WITH ARMRESTS 2BR.jpg#LILLE 2,5 SEATER WITH ARMRESTS 3BR.jpg#LILLE 2,5 SEATER WITH ARMRESTS 4BR.jpg'	],
            ['product_id' =>	6	, 'color_id' =>	1	, 'src' =>	'ZURICH SOFA WITH RESTING UNIT1.jpg#ZURICH SOFA WITH RESTING UNIT2.jpg#ZURICH SOFA WITH RESTING UNIT3.jpg#ZURICH SOFA WITH RESTING UNIT4.jpg'	],
            ['product_id' =>	6	, 'color_id' =>	2	, 'src' =>	'ZURICH SOFA WITH RESTING UNIT 1BE.jpg#ZURICH SOFA WITH RESTING UNIT 2BE.jpg#ZURICH SOFA WITH RESTING UNIT 3BE.jpg#ZURICH SOFA WITH RESTING UNIT 4BE.jpg'	],
            ['product_id' =>	6	, 'color_id' =>	5	, 'src' =>	'ZURICH SOFA WITH RESTING UNIT 1BR.jpg#ZURICH SOFA WITH RESTING UNIT 2BR.jpg#ZURICH SOFA WITH RESTING UNIT 3BR.jpg#ZURICH SOFA WITH RESTING UNIT 4BR.jpg'	],
            ['product_id' =>	7	, 'color_id' =>	6	, 'src' =>	'FARGO SOFA1.jpg#FARGO SOFA2.jpg#FARGO SOFA3.jpg#FARGO SOFA4.jpg'	],
            ['product_id' =>	7	, 'color_id' =>	1	, 'src' =>	'FARGO SOFA 1W.jpg#FARGO SOFA 2W.jpg#FARGO SOFA 3W.jpg#FARGO SOFA 4W.jpg'	],
            ['product_id' =>	7	, 'color_id' =>	4	, 'src' =>	'FARGO SOFA 1B.jpg#FARGO SOFA 2B.jpg#FARGO SOFA 3B.jpg#FARGO SOFA B.jpg'	],
            ['product_id' =>	8	, 'color_id' =>	4	, 'src' =>	'OTTAWA SOFA1.jpg#OTTAWA SOFA2.jpg#OTTAWA SOFA3.jpg#OTTAWA SOFA4.jpg'	],
            ['product_id' =>	8	, 'color_id' =>	2	, 'src' =>	'OTTAWA SOFA 1BE.jpg#OTTAWA SOFA 2BE.jpg#OTTAWA SOFA 3BE.jpg#OTTAWA SOFA 4BE.jpg'	],
            ['product_id' =>	8	, 'color_id' =>	3	, 'src' =>	'OTTAWA SOFA 1G.jpg#OTTAWA SOFA 2G.jpg#OTTAWA SOFA 3G.jpg#OTTAWA SOFA 4G.jpg'	],
            ['product_id' =>	9	, 'color_id' =>	4	, 'src' =>	'HAMPTON SOFA WITH ADJUSTABLE BACK AND STORAGE ON THE RIGHT SIDE1.jpg#HAMPTON SOFA WITH ADJUSTABLE BACK AND STORAGE ON THE RIGHT SIDE2.jpg#HAMPTON SOFA WITH ADJUSTABLE BACK AND STORAGE ON THE RIGHT SIDE3.jpg#HAMPTON SOFA WITH ADJUSTABLE BACK AND STORAGE ON THE RIGHT SIDE4.jpg'	],
            ['product_id' =>	9	, 'color_id' =>	2	, 'src' =>	'HAMPTON SOFA WITH ADJUSTABLE BACK AND STORAGE ON THE RIGHT SIDE 1BE.jpg#HAMPTON SOFA WITH ADJUSTABLE BACK AND STORAGE ON THE RIGHT SIDE 2BE.jpg#HAMPTON SOFA WITH ADJUSTABLE BACK AND STORAGE ON THE RIGHT SIDE 3BE.jpg#HAMPTON SOFA WITH ADJUSTABLE BACK AND STORAGE ON THE RIGHT SIDE 4BE.jpg'	],
            ['product_id' =>	9	, 'color_id' =>	3	, 'src' =>	'HAMPTON SOFA WITH ADJUSTABLE BACK AND STORAGE ON THE RIGHT SIDE 1G.jpg#HAMPTON SOFA WITH ADJUSTABLE BACK AND STORAGE ON THE RIGHT SIDE 2G.jpg#HAMPTON SOFA WITH ADJUSTABLE BACK AND STORAGE ON THE RIGHT SIDE 3G.jpg#HAMPTON SOFA WITH ADJUSTABLE BACK AND STORAGE ON THE RIGHT SIDE 4G.jpg'	],
            ['product_id' =>	10	, 'color_id' =>	1	, 'src' =>	'CARMO SOFA WITH LOUNGING AND RESTING UNIT1.jpg#CARMO SOFA WITH LOUNGING AND RESTING UNIT2.jpg#CARMO SOFA WITH LOUNGING AND RESTING UNIT3.jpg#CARMO SOFA WITH LOUNGING AND RESTING UNIT4.jpg'	],
            ['product_id' =>	10	, 'color_id' =>	5	, 'src' =>	'CARMO SOFA WITH LOUNGING AND RESTING UNIT 1BR.jpg#CARMO SOFA WITH LOUNGING AND RESTING UNIT 2BR.jpg#CARMO SOFA WITH LOUNGING AND RESTING UNIT 3BR.jpg#CARMO SOFA WITH LOUNGING AND RESTING UNIT 4BR.jpg'	],
            ['product_id' =>	10	, 'color_id' =>	3	, 'src' =>	'CARMO SOFA WITH LOUNGING AND RESTING UNIT 1G.jpg#CARMO SOFA WITH LOUNGING AND RESTING UNIT 2G.jpg#CARMO SOFA WITH LOUNGING AND RESTING UNIT 3G.jpg#CARMO SOFA WITH LOUNGING AND RESTING UNIT 4G.jpg'	],
            ['product_id' =>	11	, 'color_id' =>	2	, 'src' =>	'MODENA CHAIR1.jpg#MODENA CHAIR2.jpg#MODENA CHAIR3.jpg#MODENA CHAIR4.jpg'	],
            ['product_id' =>	12	, 'color_id' =>	2	, 'src' =>	'CHELSEA CHAIR1.jpg#CHELSEA CHAIR2.jpg#CHELSEA CHAIR3.jpg#CHELSEA CHAIR4.jpg'	],
            ['product_id' =>	13	, 'color_id' =>	3	, 'src' =>	'CARMO CHAIR1.jpg#CARMO CHAIR2.jpg#CARMO CHAIR3.jpg#CARMO CHAIR4.jpg'	],
            ['product_id' =>	14	, 'color_id' =>	2	, 'src' =>	'FUSION CHAIR1.jpg#FUSION CHAIR2.jpg#FUSION CHAIR3.jpg#FUSION CHAIR4.jpg'	],
            ['product_id' =>	15	, 'color_id' =>	1	, 'src' =>	'FLY CHAIR1.jpg#FLY CHAIR2.jpg#FLY CHAIR3.jpg#FLY CHAIR4.jpg'	],
            ['product_id' =>	16	, 'color_id' =>	4	, 'src' =>	'OSAKA CHAIR1.jpg#OSAKA CHAIR2.jpg#OSAKA CHAIR3.jpg#OSAKA CHAIR4.jpg'	],
            ['product_id' =>	17	, 'color_id' =>	2	, 'src' =>	'VENETO CHAIR WITH SWIVEL FUNCTION1.jpg#VENETO CHAIR WITH SWIVEL FUNCTION2.jpg#VENETO CHAIR WITH SWIVEL FUNCTION3.jpg#VENETO CHAIR WITH SWIVEL FUNCTION4.jpg'	],
            ['product_id' =>	18	, 'color_id' =>	6	, 'src' =>	'IMOLA CHAIR1.jpg#IMOLA CHAIR2.jpg#IMOLA CHAIR3.jpg#IMOLA CHAIR4.jpg'	],
            ['product_id' =>	19	, 'color_id' =>	2	, 'src' =>	'DUBLIN CHAIR1.jpg#DUBLIN CHAIR3.jpg#DUBLIN CHAIR3.jpg#DUBLIN CHAIR4.jpg'	],
            ['product_id' =>	20	, 'color_id' =>	6	, 'src' =>	'ATHENA CHAIR WITH RECLINING BACK FUNCTION1.jpg#ATHENA CHAIR WITH RECLINING BACK FUNCTION2.jpg#ATHENA CHAIR WITH RECLINING BACK FUNCTION3.jpg#ATHENA CHAIR WITH RECLINING BACK FUNCTION4.jpg'	],
            ['product_id' =>	21	, 'color_id' =>	1	, 'src' =>	'PRINCETON CHAIR1.jpg#PRINCETON CHAIR2.jpg#PRINCETON CHAIR3.jpg#PRINCETON CHAIR4.jpg'	],
            ['product_id' =>	22	, 'color_id' =>	5	, 'src' =>	'NEWPORT CHAIR1.jpg#NEWPORT CHAIR2.jpg#NEWPORT CHAIR3.jpg#NEWPORT CHAIR4.jpg'	],
            ['product_id' =>	23	, 'color_id' =>	1	, 'src' =>	'OTTAWA CHAIR1.jpg#OTTAWA CHAIR2.jpg#OTTAWA CHAIR3.jpg#OTTAWA CHAIR4.jpg'	],
            ['product_id' =>	24	, 'color_id' =>	3	, 'src' =>	'ADELAIDE BARSTOOL1.jpg#ADELAIDE BARSTOOL2.jpg#ADELAIDE BARSTOOL3.jpg#ADELAIDE BARSTOOL4.jpg'	],
            ['product_id' =>	25	, 'color_id' =>	6	, 'src' =>	'ELBA CHAIR1.jpg#ELBA CHAIR2.jpg#ELBA CHAIR3.jpg#ELBA CHAIR4.jpg'	],
            ['product_id' =>	26	, 'color_id' =>	2	, 'src' =>	'LAUSANNE CHAIR1.jpg#LAUSANNE CHAIR2.jpg#LAUSANNE CHAIR3.jpg#LAUSANNE CHAIR4.jpg'	],
            ['product_id' =>	27	, 'color_id' =>	5	, 'src' =>	'ADELAIDE CHAIR WITH SWIVEL FUNCTION1.jpg#ADELAIDE CHAIR WITH SWIVEL FUNCTION2.jpg#ADELAIDE CHAIR WITH SWIVEL FUNCTION3.jpg#ADELAIDE CHAIR WITH SWIVEL FUNCTION4.jpg'	],
            ['product_id' =>	28	, 'color_id' =>	1	, 'src' =>	'ADELAIDE CHAIR1.jpg#ADELAIDE CHAIR2.jpg#ADELAIDE CHAIR3.jpg#ADELAIDE CHAIR4.jpg'	],
            ['product_id' =>	29	, 'color_id' =>	4	, 'src' =>	'ADELAIDE CHAIR WITH SWIVEL FUNCTION AND WHEELS1.jpg#ADELAIDE CHAIR WITH SWIVEL FUNCTION AND WHEELS2.jpg#ADELAIDE CHAIR WITH SWIVEL FUNCTION AND WHEELS3.jpg#ADELAIDE CHAIR WITH SWIVEL FUNCTION AND WHEELS4.jpg'	],
            ['product_id' =>	30	, 'color_id' =>	3	, 'src' =>	'BOSTON CHAIR WITH SWIVEL FUNCTION1.jpg#BOSTON CHAIR WITH SWIVEL FUNCTION2.jpg#BOSTON CHAIR WITH SWIVEL FUNCTION3.jpg#BOSTON CHAIR WITH SWIVEL FUNCTION4.jpg'	],
            ['product_id' =>	31	, 'color_id' =>	1	, 'src' =>	'ALICANTE TABLE WITH SUPPLEMENTARY TABLETOP1.jpg#ALICANTE TABLE WITH SUPPLEMENTARY TABLETOP2.jpg#ALICANTE TABLE WITH SUPPLEMENTARY TABLETOP3.jpg#ALICANTE TABLE WITH SUPPLEMENTARY TABLETOP4.jpg'	],
            ['product_id' =>	32	, 'color_id' =>	1	, 'src' =>	'MADRID COFFEE TABLE1.jpg#MADRID COFFEE TABLE2.jpg#MADRID COFFEE TABLE3.jpg#MADRID COFFEE TABLE4.jpg'	],
            ['product_id' =>	33	, 'color_id' =>	5	, 'src' =>	'CUPERTINO DESK1.jpg#CUPERTINO DESK2.jpg#CUPERTINO DESK3.jpg#CUPERTINO DESK4.jpg'	],
            ['product_id' =>	34	, 'color_id' =>	2	, 'src' =>	'CHIVA FUNCTIONAL COFFEE TABLE WITH STORAGE1.jpg#CHIVA FUNCTIONAL COFFEE TABLE WITH STORAGE2.jpg#CHIVA FUNCTIONAL COFFEE TABLE WITH STORAGE3.jpg#CHIVA FUNCTIONAL COFFEE TABLE WITH STORAGE4.jpg'	],
            ['product_id' =>	35	, 'color_id' =>	6	, 'src' =>	'PARIS SIDE TABLE1.jpg#PARIS SIDE TABLE2.jpg#PARIS SIDE TABLE3.jpg#PARIS SIDE TABLE4.jpg'	],
            ['product_id' =>	36	, 'color_id' =>	6	, 'src' =>	'EXPOSE SIDE TABLE1.jpg#EXPOSE SIDE TABLE2.jpg#EXPOSE SIDE TABLE3.jpg#EXPOSE SIDE TABLE4.jpg'	],
            ['product_id' =>	37	, 'color_id' =>	5	, 'src' =>	'RUBI ADJUSTABLE TABLE1.jpg#RUBI ADJUSTABLE TABLE2.jpg#RUBI ADJUSTABLE TABLE3.jpg#RUBI ADJUSTABLE TABLE4.jpg'	],
            ['product_id' =>	38	, 'color_id' =>	1	, 'src' =>	'ELBA TABLE1.jpg#ELBA TABLE2.jpg#ELBA TABLE3.jpg#ELBA TABLE4.jpg'	],
            ['product_id' =>	39	, 'color_id' =>	6	, 'src' =>	'PHOENIX ELECTRIC OFFICE DESK1.jpg#PHOENIX ELECTRIC OFFICE DESK2.jpg#PHOENIX ELECTRIC OFFICE DESK3.jpg#PHOENIX ELECTRIC OFFICE DESK4.jpg'	],
            ['product_id' =>	40	, 'color_id' =>	1	, 'src' =>	'BILLUND TABLE1.jpg#BILLUND TABLE2.jpg#BILLUND TABLE3.jpg#BILLUND TABLE4.jpg'	],
            ['product_id' =>	41	, 'color_id' =>	1	, 'src' =>	'FERMO SIDEBOARD LARGE1.jpg#FERMO SIDEBOARD LARGE2.jpg#FERMO SIDEBOARD LARGE3.jpg#FERMO SIDEBOARD LARGE4.jpg'	],
            ['product_id' =>	42	, 'color_id' =>	6	, 'src' =>	'COPENHAGEN OFFICE SYSTEM1.jpg#COPENHAGEN OFFICE SYSTEM2.jpg#COPENHAGEN OFFICE SYSTEM3.jpg#COPENHAGEN OFFICE SYSTEM4.jpg'	],
            ['product_id' =>	43	, 'color_id' =>	3	, 'src' =>	'COPENHAGEN WALL SYSTEM1.jpg#COPENHAGEN WALL SYSTEM2.jpg#COPENHAGEN WALL SYSTEM3.jpg#COPENHAGEN WALL SYSTEM4.jpg'	],
            ['product_id' =>	44	, 'color_id' =>	2	, 'src' =>	'COMO BOOKCASE1.jpg#COMO BOOKCASE2.jpg#COMO BOOKCASE3.jpg#COMO BOOKCASE4.jpg'	],
            ['product_id' =>	45	, 'color_id' =>	2	, 'src' =>	'BORDEAUX CONSOLE TABLE1.jpg#BORDEAUX CONSOLE TABLE2.jpg#BORDEAUX CONSOLE TABLE3.jpg#BORDEAUX CONSOLE TABLE4.jpg'	],
            ['product_id' =>	46	, 'color_id' =>	5	, 'src' =>	'ATLANTA BASE CABINET WITH DRAWERS AND BOOKCASE1.jpg#ATLANTA BASE CABINET WITH DRAWERS AND BOOKCASE2.jpg#ATLANTA BASE CABINET WITH DRAWERS AND BOOKCASE3.jpg#ATLANTA BASE CABINET WITH DRAWERS AND BOOKCASE4.jpg'	],
            ['product_id' =>	47	, 'color_id' =>	1	, 'src' =>	'OTTAWA SIDEBOARD1.jpg#OTTAWA SIDEBOARD2.jpg#OTTAWA SIDEBOARD3.jpg#OTTAWA SIDEBOARD4.jpg'	],
            ['product_id' =>	48	, 'color_id' =>	2	, 'src' =>	'COPENHAGEN WALL1.jpg#COPENHAGEN WALL2.jpg#COPENHAGEN WALL3.jpg#COPENHAGEN WALL4.jpg'	],
            ['product_id' =>	49	, 'color_id' =>	5	, 'src' =>	'ATLANTA BASE CABINET WITH DOORS AND BOOKCASE1.jpg#ATLANTA BASE CABINET WITH DOORS AND BOOKCASE2.jpg#ATLANTA BASE CABINET WITH DOORS AND BOOKCASE3.jpg#ATLANTA BASE CABINET WITH DOORS AND BOOKCASE4.jpg'	],
            ['product_id' =>	50	, 'color_id' =>	6	, 'src' =>	'BORDEAUX WALL1.jpg#BORDEAUX WALL2.jpg#BORDEAUX WALL3.jpg#BORDEAUX WALL4.jpg'	],
            ['product_id' =>	51	, 'color_id' =>	2	, 'src' =>	'AUSTIN BED EXCL MATTRESS1.jpg#AUSTIN BED EXCL MATTRESS2.jpg#AUSTIN BED EXCL MATTRESS3.jpg#AUSTIN BED EXCL MATTRESS4.jpg'	],
            ['product_id' =>	52	, 'color_id' =>	4	, 'src' =>	'ARLINGTON BED EXCL MATTRESS1.jpg#ARLINGTON BED EXCL MATTRESS2.jpg#ARLINGTON BED EXCL MATTRESS3.jpg#ARLINGTON BED EXCL MATTRESS4.jpg'	],
            ['product_id' =>	53	, 'color_id' =>	2	, 'src' =>	'HOUSTON UPHOLSTERED BED WITH STORAGE1.jpg#HOUSTON UPHOLSTERED BED WITH STORAGE2.jpg#HOUSTON UPHOLSTERED BED WITH STORAGE3.jpg#HOUSTON UPHOLSTERED BED WITH STORAGE4.jpg'	],
            ['product_id' =>	54	, 'color_id' =>	3	, 'src' =>	'LUGANO STORAGE BED WITH LIFT-UP FRAME AND SLATS1.jpg#LUGANO STORAGE BED WITH LIFT-UP FRAME AND SLATS2.jpg#LUGANO STORAGE BED WITH LIFT-UP FRAME AND SLATS3.jpg#LUGANO STORAGE BED WITH LIFT-UP FRAME AND SLATS4.jpg'	],
            ['product_id' =>	55	, 'color_id' =>	2	, 'src' =>	'MEZZO BED EXCL MATTRESS1.jpg#MEZZO BED EXCL MATTRESS2.jpg#MEZZO BED EXCL MATTRESS3.jpg#MEZZO BED EXCL MATTRESS4.jpg'	],
            ['product_id' =>	56	, 'color_id' =>	1	, 'src' =>	'LUGANO BED EXCL MATTRESS1.jpg#LUGANO BED EXCL MATTRESS2.jpg#LUGANO BED EXCL MATTRESS3.jpg#LUGANO BED EXCL MATTRESS4.jpg'	],
            ['product_id' =>	57	, 'color_id' =>	1	, 'src' =>	'LUGANO WITHOUT HEADBOARD WITH SLATS AND LEGS1.jpg#LUGANO WITHOUT HEADBOARD WITH SLATS AND LEGS2.jpg#LUGANO WITHOUT HEADBOARD WITH SLATS AND LEGS3.jpg#LUGANO WITHOUT HEADBOARD WITH SLATS AND LEGS4.jpg'	],
            ['product_id' =>	58	, 'color_id' =>	2	, 'src' =>	'LUGANO STORAGE BED WITH LIFTUP FRAME AND SLATS EXCL MATTRESS1.jpg#LUGANO STORAGE BED WITH LIFTUP FRAME AND SLATS EXCL MATTRESS2.jpg#LUGANO STORAGE BED WITH LIFTUP FRAME AND SLATS EXCL MATTRESS3.jpg#LUGANO STORAGE BED WITH LIFTUP FRAME AND SLATS EXCL MATTRESS4.jpg'	],
            ['product_id' =>	59	, 'color_id' =>	3	, 'src' =>	'HOUSTON BED EXCL MATTRESS1.jpg#HOUSTON BED EXCL MATTRESS2.jpg#HOUSTON BED EXCL MATTRESS3.jpg#HOUSTON BED EXCL MATTRESS4.jpg'	],
            ['product_id' =>	60	, 'color_id' =>	3	, 'src' =>	'MEZZO STORAGE BED WITH LIFTUP FRAME AND SLATS EXCL MATTRESS1.jpg#MEZZO STORAGE BED WITH LIFTUP FRAME AND SLATS EXCL MATTRESS2.jpg#MEZZO STORAGE BED WITH LIFTUP FRAME AND SLATS EXCL MATTRESS3.jpg#MEZZO STORAGE BED WITH LIFTUP FRAME AND SLATS EXCL MATTRESS4.jpg'	],
            ['product_id' =>	61	, 'color_id' =>	3	, 'src' =>	'KUTA FLOOR LAMP1.jpg#KUTA FLOOR LAMP2.jpg#KUTA FLOOR LAMP3.jpg#KUTA FLOOR LAMP4.jpg'	],
            ['product_id' =>	62	, 'color_id' =>	5	, 'src' =>	'PINE CONE PENDANT1.jpg#PINE CONE PENDANT2.jpg#PINE CONE PENDANT3.jpg#PINE CONE PENDANT4.jpg'	],
            ['product_id' =>	63	, 'color_id' =>	1	, 'src' =>	'DAWN TABLE LAMP1.jpg#DAWN TABLE LAMP2.jpg#DAWN TABLE LAMP3.jpg#DAWN TABLE LAMP4.jpg'	],
            ['product_id' =>	64	, 'color_id' =>	6	, 'src' =>	'QUADRO WALL LAMP1.jpg#QUADRO WALL LAMP2.jpg#QUADRO WALL LAMP3.jpg#QUADRO WALL LAMP4.jpg'	],
            ['product_id' =>	65	, 'color_id' =>	3	, 'src' =>	'SHELTER TABLE LAMP1.jpg#SHELTER TABLE LAMP2.jpg#SHELTER TABLE LAMP3.jpg#SHELTER TABLE LAMP4.jpg'	],
            ['product_id' =>	66	, 'color_id' =>	6	, 'src' =>	'LEVEL PENDANT1.jpg#LEVEL PENDANT2.jpg#LEVEL PENDANT3.jpg#LEVEL PENDANT4.jpg'	],
            ['product_id' =>	67	, 'color_id' =>	5	, 'src' =>	'FIVE CHANDELIER1.jpg#FIVE CHANDELIER2.jpg#FIVE CHANDELIER3.jpg#FIVE CHANDELIER4.jpg'	],
            ['product_id' =>	68	, 'color_id' =>	6	, 'src' =>	'CURIOUS FLOOR LAMP1.jpg#CURIOUS FLOOR LAMP2.jpg#CURIOUS FLOOR LAMP3.jpg#CURIOUS FLOOR LAMP4.jpg'	],
            ['product_id' =>	69	, 'color_id' =>	6	, 'src' =>	'DEMAND TABLE LAMP1.jpg#DEMAND TABLE LAMP2.jpg#DEMAND TABLE LAMP3.jpg#DEMAND TABLE LAMP4.jpg'	],
            ['product_id' =>	70	, 'color_id' =>	5	, 'src' =>	'STOCKHOLM TABLE LAMP1.jpg#STOCKHOLM TABLE LAMP2.jpg#STOCKHOLM TABLE LAMP3.jpg#STOCKHOLM TABLE LAMP4.jpg'	],            
        ]);
    }
}
