<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Faker\Factory as Faker;
use Illuminate\Support\Facades\DB;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */

    protected $faker;

    public function __construct()
    {
        $this->faker = Faker::create();
    }

    public function run()
    {
        DB::table('products')->insert([
            [
                'product_name' =>    'MODENA 2,5 SEATER',
                'category_id' =>    1, 'price' =>    51110000,
                'brand_id' =>    3,
                'description' =>    'Organic shapes and minimal lines come together in a casual, contemporary expression. The Modena chair will add a comfy vibe that calls for you to come lounge in excellent seating comfort. Elegant design details lift the overall expression and together with the soft comfort, ensure a chair that quickly will become your favourite relaxing spot.',
                'dimension_id' =>    1,
                'quantity' => 5,
                'sale_amount' => 5,
                'discount_id' => 0,
                'created_at' => $this->faker->dateTimeBetween('2010-01-01'),
            ],
            [
                'product_name' =>    'HAMPTON CORNER SOFA WITH ADJUSTABLE BACK AND STORAGE ON RIGHT SIDE',
                'category_id' =>    1,
                'price' =>    165480000,
                'brand_id' =>    3,
                'description' =>    'We know. It’s beautiful. But the modern Hampton sofa is much more than just good looks. A low base, a stunning loft look, adjustable backrests for comfort and visual impact – the Hampton sofa is the perfect personal retreat. With plenty of room for the entire family this corner sofa will be the hero of your living room',
                'dimension_id' =>    2,
                'quantity' => 15,
                'sale_amount' => 3,
                'discount_id' => 0,
                'created_at' => $this->faker->dateTimeBetween('2010-01-01'),
            ],
            [
                'product_name' =>    'AMSTERDAM RESTING MODULE FOR SOFA, ARMREST RIGHT',
                'category_id' =>    1,
                'price' =>    133880000,
                'brand_id' =>    4,
                'description' =>    'Amsterdam is sharp lines and sweeping curves. Comfort and luxury imbue every detail to make Amsterdam the perfect sofa for a soft and inviting statement in your living room.',
                'dimension_id' =>    3,
                'quantity' => 35,
                'sale_amount' => 7,
                'created_at' => $this->faker->dateTimeBetween('2010-01-01'),
            ],
            [
                'product_name' =>    'AMSTERDAM 2,5 SEATING MODULE, ARMREST LEFT',
                'category_id' =>    1,
                'price' =>    80550000,
                'brand_id' =>    1,
                'description' =>    'Amsterdam is sharp lines and sweeping curves. Comfort and luxury imbue every detail to make Amsterdam the perfect sofa for a soft and inviting statement in your living room.',
                'dimension_id' =>    4,
                'quantity' => 25,
                'sale_amount' => 3,
                'created_at' => $this->faker->dateTimeBetween('2010-01-01'),
            ],
            [
                'product_name' =>    'Lille 2,5 seater with armrests',
                'category_id' =>    1,
                'price' =>    43320000,
                'brand_id' =>    4,
                'description' =>    'Feel the embrace of Danish design in the comfortable yet elegant Lille sofa. The design is minimal yet organic and expressive - perfect for small spaces in need of comfort and style.',
                'dimension_id' =>    5,
                'quantity' => 15,
                'sale_amount' => 5,
                'created_at' => $this->faker->dateTimeBetween('2010-01-01'),
            ],
            [
                'product_name' =>    'ZURICH SOFA WITH RESTING UNIT',
                'category_id' =>    1,
                'price' =>    98300000,
                'brand_id' =>    3,
                'description' =>    'The Zurich sofa is your personal design statement with adjustable headrest and ultimate comfort. The sofa offers a light appearance making it perfect for both small and larger spaces as well as details that make it superb in both leather and fabric. It’s coziness and luxury in one perfect expression.',
                'dimension_id' =>    6,
                'quantity' => 15,
                'sale_amount' => 3,
                'created_at' => $this->faker->dateTimeBetween('2010-01-01'),
            ],
            [
                'product_name' =>    'FARGO SOFA',
                'category_id' =>    1,
                'price' =>    120460000,
                'brand_id' =>    2,
                'description' =>    'The feminine look and curvy features of the exclusive Fargo sofa will add a sense of softness to your living room and create a welcoming atmosphere. Cosy up with your family or claim the sofa all to yourself with this roomy 3 seater sofa.',
                'dimension_id' =>    7,
                'quantity' => 9,
                'sale_amount' => 1,
                'created_at' => $this->faker->dateTimeBetween('2010-01-01'),
            ],
            [
                'product_name' =>    'OTTAWA SOFA',
                'category_id' =>    1,
                'price' =>    58820000,
                'brand_id' =>    4,
                'description' =>    "Got a creative mind? Designer Karim Rashid surely does, and with Ottawa he invites you to play and customize. Ottawa has a tight look but is an extremely flexible concept, inviting you to create your own space. While keeping the 2 seater look, this comfortable 2.5 seater sofa has wider seats for extra comfort.",
                'dimension_id' =>    8,
                'quantity' => 5,
                'sale_amount' => 3,
                'created_at' => $this->faker->dateTimeBetween('2010-01-01'),
            ],
            [
                'product_name' =>    "HAMPTON SOFA WITH ADJUSTABLE BACK AND STORAGE ON THE RIGHT SIDE",
                'category_id' =>    1,
                'price' =>    165480000,
                'brand_id' =>    6,
                'description' =>    'We know. It’s beautiful. But the modern Hampton sofa is much more than just good looks. A low base, a stunning loft look, adjustable backrests for comfort and visual impact – the Hampton sofa is the perfect personal retreat. Cosy up with your family or claim the sofa all to yourself with this roomy 3 seater sofa. ',
                'dimension_id' =>    9,
                'quantity' => 5,
                'sale_amount' => 0,
                'created_at' => $this->faker->dateTimeBetween('2010-01-01'),
            ],
            [
                'product_name' =>    'CARMO SOFA WITH LOUNGING AND RESTING UNIT',
                'category_id' =>    1,
                'price' =>    107050000,
                'brand_id' =>    1,
                'description' =>    'The modern Carmo sofa is a real show-stopper with its cubic look, perfectly accentuated by exclusive piping details. Don’t be fooled by the straight lines, this sofa is a dream to sit on. The open end will create a dynamic, welcoming atmosphere - a true blessing for the integrated areas of open-plan living.',
                'dimension_id' =>    10,
                'quantity' => 10,
                'sale_amount' => 2,
                'created_at' => $this->faker->dateTimeBetween('2010-01-01'),
            ],
            [
                'product_name' =>    'MODENA CHAIR',
                'category_id' =>    2,
                'price' =>    30400000,
                'brand_id' =>    3,
                'description' =>    'Organic shapes and minimal lines come together in a casual, contemporary expression. The Modena chair will add a comfy vibe that calls for you to come lounge in excellent seating comfort.',
                'dimension_id' =>    11,
                'quantity' => 4,
                'sale_amount' => 10,
                'created_at' => $this->faker->dateTimeBetween('2010-01-01'),
            ],
            [
                'product_name' =>    'CHELSEA CHAIR',
                'category_id' =>    2,
                'price' =>    51650000,
                'brand_id' =>    6,
                'description' =>    'Chelsea is Karim Rashid’s take on feminine, soft and organic design that adds a sensual comfort to your space. It’s an eye-catching statement piece inspired by the Chelsea neighbourhood of New York City – the art hub and home of the prolific designer.',
                'dimension_id' =>    12,
                'quantity' => 5,
                'sale_amount' => 5,
                'created_at' => $this->faker->dateTimeBetween('2010-01-01'),
            ],
            [
                'product_name' =>    'CARMO CHAIR',
                'category_id' =>    2,
                'price' =>    33590000,
                'brand_id' =>    6,
                'description' =>    'Whether it’s working together with the matching Carmo sofa or rocking it solo as a cosy and stylish corner seat, the Carmo ottoman certainly makes an impact. Don’t be fooled by the cubic look and straight lines, this ottoman packs just as much comfort as character.',
                'dimension_id' =>    13,
                'quantity' => 5,
                'sale_amount' => 5,
                'created_at' => $this->faker->dateTimeBetween('2010-01-01'),
            ],
            [
                'product_name' =>    'FUSION CHAIR',
                'category_id' =>    2,
                'price' =>    58590000,
                'brand_id' =>    5,
                'description' =>    'The fusion armchair, inspired by the art of origami, has a unique sculptural look and a plump seat just waiting to give you a hug. With slim wooden legs to lighten the look of the heavy seat, this is an armchair dying to make a design statement in your living room.',
                'dimension_id' =>    14,
                'quantity' => 9,
                'sale_amount' => 2,
                'created_at' => $this->faker->dateTimeBetween('2010-01-01'),
            ],
            [
                'product_name' =>    'FLY CHAIR',
                'category_id' =>    2,
                'price' =>    68590000,
                'brand_id' =>    3,
                'description' =>    'Looking sleek and stylish, the classic Fly armchair is definitely cool. With a comfort your body will thank you for and a design that’ll look great in most living rooms, the Fly armchair is ready to be a part of your home.',
                'dimension_id' =>    15,
                'quantity' => 10,
                'sale_amount' => 3,
                'created_at' => $this->faker->dateTimeBetween('2010-01-01'),
            ],
            [
                'product_name' =>    'OSAKA CHAIR',
                'category_id' =>    2,
                'price' =>    21490000,
                'brand_id' =>    3,
                'description' =>    'With a feminine touch and a nod to 60s design, the Osaka armchair is all about style. The light design and slim proportions make this armchair perfect for small homes or as part of a style coordinated living room set with the Osaka sofa. The beautiful tufted seat adds visual softness and brings a classic look to your living room.',
                'dimension_id' =>    16,
                'quantity' => 6,
                'sale_amount' => 1,
                'created_at' => $this->faker->dateTimeBetween('2010-01-01'),
            ],
            [
                'product_name' =>    'VENETO CHAIR WITH SWIVEL FUNCTION',
                'category_id' =>    2,
                'price' =>    33590000,
                'brand_id' =>    5,
                'description' =>    'Lounge like you’re at a trendy club in the stylish Veneto armchair. Looking low and lovely this club-inspired armchair is just the thing for entertaining friends. The organic, unbroken lines of the design provide a casual cool look while bringing a dynamic atmosphere to you home.',
                'dimension_id' =>    17,
                'quantity' => 25,
                'sale_amount' => 15,
                'created_at' => $this->faker->dateTimeBetween('2010-01-01'),
            ],
            [
                'product_name' =>    'IMOLA CHAIR',
                'category_id' =>    2,
                'price' =>    110790000,
                'brand_id' =>    4,
                'description' =>    'Take a closer look. From the striking details to the graceful sweeps of its curves, the Imola armchair is a true design icon. Roomy enough for you to curl up in, yet so elegant it doesn’t seem over the top, the Imola armchair is an instant classic and ready to make a statement in your home.',
                'dimension_id' =>    18,
                'quantity' => 10,
                'sale_amount' => 4,
                'created_at' => $this->faker->dateTimeBetween('2010-01-01'),
            ],
            [
                'product_name' =>    'DUBLIN CHAIR',
                'category_id' =>    2,
                'price' =>    5000000,
                'brand_id' =>    5,
                'description' =>    'Dublin – your personal retreat with generous proportions, oversized comfort, and an attitude larger than life. The shapes of Dublin are easy on the eye, organic like pebbles on the beach, yet well-defined and with a clear purpose. With Dublin you will add comfort and an iconic expression to your home.',
                'dimension_id' =>    19,
                'quantity' => 5,
                'sale_amount' => 15,
                'created_at' => $this->faker->dateTimeBetween('2010-01-01'),
            ],
            [
                'product_name' =>    'ATHENA CHAIR WITH RECLINING BACK FUNCTION',
                'category_id' =>    2,
                'price' =>    55930000,
                'brand_id' =>    3,
                'description' =>    'A private escape. Striking beauty, hugging shapes and a seating comfort out of this world – that is the essence of the Athena recliner chair. Inviting you in with its soft flowing lines and feminine appearance, this modern recliner chair is dressed to impress. Fitted with a swivel base that turns this chair so seamlessly, you’ll want to take it for a spin.',
                'dimension_id' =>    20,
                'quantity' => 15,
                'sale_amount' => 5,
                'created_at' => $this->faker->dateTimeBetween('2010-01-01'),
            ],
            [
                'product_name' =>    'PRINCETON CHAIR',
                'category_id' =>    3,
                'price' =>    6810000,
                'brand_id' =>    4,
                'description' =>    'Elegance and comfort beautifully combine in the Princeton chair. The visual appeal of the chair invites you to explore how every curve adds both comfort and looks. Enjoy the elegant embrace of Princeton and add a feminine, exquisite touch to your dining space.',
                'dimension_id' =>    21,
                'quantity' => 9,
                'sale_amount' => 2,
                'created_at' => $this->faker->dateTimeBetween('2010-01-01'),
            ],
            [
                'product_name' =>    'NEWPORT CHAIR',
                'category_id' =>    3,
                'price' =>    16190000,
                'brand_id' =>    1,
                'description' =>    'The Newport chair is an elegant, light and functional chair with exclusive details in the back and legs. The artistic symbiosis of a light base and compact seat allows for work with the upholstery options for vibrant and complementary looks',
                'dimension_id' =>    22,
                'quantity' => 5,
                'sale_amount' => 55,
                'created_at' => $this->faker->dateTimeBetween('2010-01-01'),
            ],
            [
                'product_name' =>    'OTTAWA CHAIR',
                'category_id' =>    3,
                'price' =>    5590000,
                'brand_id' =>    4,
                'description' =>    'Visibly inspired by nature with its leaf-shape and curved design, the Ottawa dining chair is truly a unique piece of design furniture. Once you are seated, you will discover that the Ottawa chair is not only characteristic in looks, but also in comfort. The twig-like legs on Ottawa add to the organic chair design, completing its unique look.',
                'dimension_id' =>    23,
                'quantity' => 5,
                'sale_amount' => 7,
                'created_at' => $this->faker->dateTimeBetween('2010-01-01'),
            ],
            [
                'product_name' =>    'ADELAIDE BARSTOOL',
                'category_id' =>    3,
                'price' =>    16510000,
                'brand_id' =>    3,
                'description' =>    'Hop on up! With its graceful look and curved beauty, the Adelaide bar stool will make you fall in love with your kitchen all over again. This modern bar stool mixes curves and character with sublime comfort and a sturdy base to rest your feet. Enjoy your morning coffee in great comfort with the fully upholstered seat.',
                'dimension_id' =>    24,
                'quantity' => 5,
                'sale_amount' => 11,
                'created_at' => $this->faker->dateTimeBetween('2010-01-01'),
            ],
            [
                'product_name' =>    'ELBA CHAIR',
                'category_id' =>    3,
                'price' =>    6890000,
                'brand_id' =>    4,
                'description' =>    'Comfortable, close to maintenance-free and with a style punch to accompany it, Elba outdoor furniture is the perfect setting for great outdoor moments. Time for a barbeque? This outdoor dining chair adds a modern elegance to your outdoor dinner parties.',
                'dimension_id' =>    25,
                'quantity' => 5,
                'sale_amount' => 22,
                'created_at' => $this->faker->dateTimeBetween('2010-01-01'),
            ],
            [
                'product_name' =>    'LAUSANNE CHAIR',
                'category_id' =>    3,
                'price' =>    10150000,
                'brand_id' =>    1,
                'description' =>    'Classy all the way. That’s one way to describe the classic Lausanne dining chair. With a high back for great support, a sloped seat edge for more comfort and a formal yet modern look, this dining chair ensures that you\'ll look great while sitting perfectly at ease at your next dinner party.',
                'dimension_id' =>    26,
                'quantity' => 5,
                'sale_amount' => 8,
                'created_at' => $this->faker->dateTimeBetween('2010-01-01'),
            ],
            [
                'product_name' =>    'ADELAIDE CHAIR WITH SWIVEL FUNCTION',
                'category_id' =>    3,
                'price' =>    26760000,
                'brand_id' =>    1,
                'description' =>    'The iconic Adelaide chair is all about curves, comfort and character. With a graceful, organic form and sublime comfort this modern chair will set an elegant tone in your home. The slender swivel base provides flexibility without compromising on the lines of the chair design.',
                'dimension_id' =>    27,
                'quantity' => 5,
                'sale_amount' => 19,
                'created_at' => $this->faker->dateTimeBetween('2010-01-01'),
            ],
            [
                'product_name' =>    'ADELAIDE CHAIR',
                'category_id' =>    3,
                'price' =>    7890000,
                'brand_id' =>    4,
                'description' =>    'The iconic Adelaide chair is all about curves, comfort and character. With a graceful, organic form and sublime comfort this modern chair will set an elegant tone in your home. Straight wooden legs give the dining chair a Scandinavian look and contrast the curved seat.',
                'dimension_id' =>    28,
                'quantity' => 40,
                'sale_amount' => 50,
                'created_at' => $this->faker->dateTimeBetween('2010-01-01'),
            ],
            [
                'product_name' =>    'ADELAIDE CHAIR WITH SWIVEL FUNCTION AND WHEELS',
                'category_id' =>    3,
                'price' =>    18810000,
                'brand_id' =>    6,
                'description' =>    'With a graceful, organic form and sublime comfort this modern chair will set an elegant tone in your home. The swivel base with wheels makes this chair very flexible and able to work as both dining chair and office chair. At the same time, the exclusive design is matched by great comfort by the fully upholstered seat.',
                'dimension_id' =>    29,
                'quantity' => 5,
                'sale_amount' => 6,
                'created_at' => $this->faker->dateTimeBetween('2010-01-01'),
            ],
            [
                'product_name' =>    'BOSTON CHAIR WITH SWIVEL FUNCTION',
                'category_id' =>    3,
                'price' =>    68310000,
                'brand_id' =>    1,
                'description' =>    'Don’t think for a second that the clean, sleek lines of the Boston armchair equal an uncomfortable seat. Though it appears slim, the thick and soft seat makes the Boston armchair as easy on the body as it is on the eyes. Let the armchair cocoon you and relax to your full potential.',
                'dimension_id' =>    30,
                'quantity' => 5,
                'sale_amount' => 0,
                'created_at' => $this->faker->dateTimeBetween('2010-01-01'),
            ],
            [
                'product_name' =>    'ALICANTE TABLE WITH SUPPLEMENTARY TABLETOP',
                'category_id' =>    4,
                'price' =>    57690000,
                'brand_id' =>    1,
                'description' =>    'Don’t think for a second that the clean, sleek lines of the Boston armchair equal an uncomfortable seat. Though it appears slim, the thick and soft seat makes the Boston armchair as easy on the body as it is on the eyes. Let the armchair cocoon you and relax to your full potential.',
                'dimension_id' =>    31,
                'quantity' => 3,
                'sale_amount' => 8,
                'created_at' => $this->faker->dateTimeBetween('2010-01-01'),
            ],
            [
                'product_name' =>    'MADRID COFFEE TABLE',
                'category_id' =>    4,
                'price' =>    32990000,
                'brand_id' =>    2,
                'description' =>    'Clean lines and organic shapes come together in a floating design to make the Madrid table a sensory, vibrant piece for your interior. Let it stand alone or combine tables for exclusive looks in your living room',
                'dimension_id' =>    32,
                'quantity' => 5,
                'sale_amount' => 5,
                'created_at' => $this->faker->dateTimeBetween('2010-01-01'),
            ],
            [
                'product_name' =>    'CUPERTINO DESK',
                'category_id' =>    4,
                'price' =>    41390000,
                'brand_id' =>    6,
                'description' =>    'Cupertino - everything you need in a home office, hidden away in an instant. The Cupertino Executive desk combines a large table top and roomy drawers with a light design, providing plenty of space for all your office essentials while keeping a minimalist look.',
                'dimension_id' =>    33,
                'quantity' => 5,
                'sale_amount' => 4,
                'created_at' => $this->faker->dateTimeBetween('2010-01-01'),
            ],
            [
                'product_name' =>    'CHIVA FUNCTIONAL COFFEE TABLE WITH STORAGE',
                'category_id' =>    4,
                'price' =>    40790000,
                'brand_id' =>    1,
                'description' =>    'This modern coffee table is pure functionality wrapped in great design. Hide your remotes, your magazines, your chargers and cables in the heart of the Chiva coffee table, with its clever integrated storage. Or raise the slim table tops to create the perfect height for afternoon tea.',
                'dimension_id' =>    34,
                'quantity' => 2,
                'sale_amount' => 8,
                'created_at' => $this->faker->dateTimeBetween('2010-01-01'),
            ],
            [
                'product_name' =>    'PARIS SIDE TABLE',
                'category_id' =>    4,
                'price' =>    11590000,
                'brand_id' =>    2,
                'description' =>    'Paris is your elegant storage solution perfect for both tight spaces and grandiose interiors. The elegant and light construction lifts the solid top in a luxurious and functional design expression.',
                'dimension_id' =>    35,
                'quantity' => 3,
                'sale_amount' => 10,
                'created_at' => $this->faker->dateTimeBetween('2010-01-01'),
            ],
            [
                'product_name' =>    'EXPOSE SIDE TABLE',
                'category_id' =>    4,
                'price' =>    10990000,
                'brand_id' =>    3,
                'description' =>    'The elegant and light construction lifts the solid top in a luxurious and functional design expression.Or raise the slim table tops to create the perfect height for afternoon tea.',
                'dimension_id' =>    36,
                'quantity' => 4,
                'sale_amount' => 4,
                'created_at' => $this->faker->dateTimeBetween('2010-01-01'),
            ],
            [
                'product_name' =>    'RUBI ADJUSTABLE TABLE',
                'category_id' =>    4,
                'price' =>    36790000,
                'brand_id' =>    2,
                'description' =>    'Small living is no hassle when you can have work area, living room and dining room in one place. The multifunctional Rubi table easily expands from a modern coffee table to a dining table seating 8 people while the clean lines ensure a tidy and modern look.',
                'dimension_id' =>    37,
                'quantity' => 9,
                'sale_amount' => 100,
                'created_at' => $this->faker->dateTimeBetween('2010-01-01'),
            ],
            [
                'product_name' =>    'ELBA TABLE',
                'category_id' =>    4,
                'price' =>    13490000,
                'brand_id' =>    3,
                'description' =>    'Comfortable, close to maintenance-free and with a style punch to accompany it, Elba outdoor furniture is the perfect setting for great outdoor moments. With low legs providing a casual chic look, this outdoor lounge table provides the perfect spot for relaxing in the sun.',
                'dimension_id' =>    38,
                'quantity' => 5,
                'sale_amount' => 10,
                'created_at' => $this->faker->dateTimeBetween('2010-01-01'),
            ],
            [
                'product_name' =>    'PHOENIX ELECTRIC OFFICE DESK',
                'category_id' =>    4,
                'price' =>    72290000,
                'brand_id' =>    2,
                'description' =>    'The Phoenix desk is your height adjustable table in a beautiful and functional design. Danish designer Morten Georgsen has composed a desk where elegant lines are perfectly complemented with the proportions and functionality that ensure an effective work day.',
                'dimension_id' =>    39,
                'quantity' => 10,
                'sale_amount' => 40,
                'created_at' => $this->faker->dateTimeBetween('2010-01-01'),
            ],
            [
                'product_name' =>    'BILLUND TABLE',
                'category_id' =>    4,
                'price' =>    21790000,
                'brand_id' =>    6,
                'description' =>    'Billund is design and function coming together in a perfect expression of Scandinavian design. The tabletop makes the table adaptable to your exact needs. Have it down for an intimate meal for two or flip it up and have room for four or five around the table.',
                'dimension_id' =>    40,
                'quantity' => 5,
                'sale_amount' => 0,
                'created_at' => $this->faker->dateTimeBetween('2010-01-01'),
            ],
            [
                'product_name' =>    'FERMO SIDEBOARD LARGE',
                'category_id' =>    5,
                'price' =>    46590000,
                'brand_id' =>    6,
                'description' =>    'Let Fermo work its magic. Watch as the clean lines and minimalist look of the Fermo extend to your entire home, when your clutter is neatly hidden away. Whether you\'re watching the game, listening to music or showing your holiday photos, this TV unit will hide your electronics seamlessly, so you can concentrate on being entertained.',
                'dimension_id' =>    41,
                'quantity' => 15,
                'sale_amount' => 65,
                'created_at' => $this->faker->dateTimeBetween('2010-01-01'),
            ],
            [
                'product_name' =>    'COPENHAGEN OFFICE SYSTEM',
                'category_id' =>    5,
                'price' =>    58490000,
                'brand_id' =>    6,
                'description' =>    'Show what you want, hide what you need! Everyone\'s storage needs are different, but the Copenhagen can take care of them all. As functional and flexible as it is beautiful, the Copenhagen is any organiser’s dream.',
                'dimension_id' =>    42,
                'quantity' => 5,
                'sale_amount' => 2,
                'created_at' => $this->faker->dateTimeBetween('2010-01-01'),
            ],
            [
                'product_name' =>    'COPENHAGEN WALL SYSTEM',
                'category_id' =>    5,
                'price' =>    133900000,
                'brand_id' =>    4,
                'description' =>    'Show what you want, hide what you need! Everyone\'s storage needs are different, but the Copenhagen can take care of them all. As functional and flexible as it is beautiful, the Copenhagen is any organiser’s dream. Show your treasures or hide your secrets with this modern wall system. Organising will never feel like a boring duty again.',
                'dimension_id' =>    43,
                'quantity' => 3,
                'sale_amount' => 10,
                'created_at' => $this->faker->dateTimeBetween('2010-01-01'),
            ],
            [
                'product_name' =>    'COMO BOOKCASE',
                'category_id' =>    5,
                'price' =>    9190000,
                'brand_id' =>    3,
                'description' =>    'Get your prized possessions out in the open. Your favourite books? Mementoes from your travels? Your designer lamp or that oh-so-stylish vase you found? They’ll all look fantastic in Como. Let your books be part of your decorations with this stylish and modern bookcase or combine multiple units to create a library.',
                'dimension_id' =>    44,
                'quantity' => 3,
                'sale_amount' => 8,
                'created_at' => $this->faker->dateTimeBetween('2010-01-01'),
            ],
            [
                'product_name' =>    'BORDEAUX CONSOLE TABLE',
                'category_id' =>    5,
                'price' =>    12590000,
                'brand_id' =>    4,
                'description' =>    'The Bordeaux console table - simple, minimalist design with a twist. Characterised by clean lines and a light structure, Bordeaux makes functionality and flexibility a thing of beauty. Utilise the space in your hallway with this console table, place it behind your sofa or let it store your books, papers and devices in your home office.',
                'dimension_id' =>    45,
                'quantity' => 5,
                'sale_amount' => 5,
                'created_at' => $this->faker->dateTimeBetween('2010-01-01'),
            ],
            [
                'product_name' =>    'ATLANTA BASE CABINET WITH DRAWERS AND BOOKCASE',
                'category_id' =>    5,
                'price' =>    71190000,
                'brand_id' =>    3,
                'description' =>    'Atlanta is your flexible and individual storage system. Mix and match different units, sizes and colours to create the perfect solution for your space. Atlanta is here to enhance the look and functionality of all rooms.',
                'dimension_id' =>    46,
                'quantity' => 5,
                'sale_amount' => 15,
                'created_at' => $this->faker->dateTimeBetween('2010-01-01'),
            ],
            [
                'product_name' =>    'OTTAWA SIDEBOARD',
                'category_id' =>    5,
                'price' =>    74890000,
                'brand_id' =>    3,
                'description' =>    'Looks cannot be said to suffer for function with this stylish sideboard. Beautiful organic curves become a fluid decoration on the Ottawa sideboard, providing both function and character to the modern design. Enjoy the ample storage space that keeps your home tidy and let the organic and unique design bring elegance to your dining room.',
                'dimension_id' =>    47,
                'quantity' => 55,
                'sale_amount' => 25,
                'created_at' => $this->faker->dateTimeBetween('2010-01-01'),
            ],
            [
                'product_name' =>    'COPENHAGEN WALL',
                'category_id' =>    5,
                'price' =>    129900000,
                'brand_id' =>    6,
                'description' =>    'Show what you want, hide what you need! Everyone\'s storage needs are different, but the Copenhagen can take care of them all. As functional and flexible as it is beautiful, the Copenhagen is any organiser’s dream. Show your treasures or hide your secrets with this modern wall system. Organising will never feel like a boring duty again.',
                'dimension_id' =>    48,
                'quantity' => 15,
                'sale_amount' => 35,
                'created_at' => $this->faker->dateTimeBetween('2010-01-01'),
            ],
            [
                'product_name' =>    'ATLANTA BASE CABINET WITH DOORS AND BOOKCASE',
                'category_id' =>    5,
                'price' =>    29590000,
                'brand_id' =>    6,
                'description' =>    'Atlanta is your flexible and individual storage system. Mix and match different units, sizes and colours to create the perfect solution for your space. Atlanta is here to enhance the look and functionality of all rooms.',
                'dimension_id' =>    49,
                'quantity' => 4,
                'sale_amount' => 17,
                'created_at' => $this->faker->dateTimeBetween('2010-01-01'),
            ],
            [
                'product_name' =>    'BORDEAUX WALL',
                'category_id' =>    5,
                'price' =>    29600000,
                'brand_id' =>    1,
                'description' =>    'Characterised by clean lines and a light structure, Bordeaux makes functionality and flexibility a thing of beauty.',
                'dimension_id' =>    50,
                'quantity' => 9,
                'sale_amount' => 7,
                'created_at' => $this->faker->dateTimeBetween('2010-01-01'),
            ],
            [
                'product_name' =>    'AUSTIN BED EXCL MATTRESS',
                'category_id' =>    6,
                'price' =>    48560000,
                'brand_id' =>    4,
                'description' =>    'Be embraced by the cocooning effect of the Austin bed. The headboard not only looks great, it defines your space and offers a comfortable place to rest. Choose your personal upholstery and create your bedroom haven.',
                'dimension_id' =>    51,
                'quantity' => 15,
                'sale_amount' => 35,
                'created_at' => $this->faker->dateTimeBetween('2010-01-01'),
            ],
            [
                'product_name' =>    'ARLINGTON BED EXCL MATTRESS',
                'category_id' =>    6,
                'price' =>    51740000,
                'brand_id' =>    2,
                'description' =>    'Great support when sitting against the headboard and a soft landing make the Arlington bed an amazing addition to the bedroom. Just like the extension of a pillow, the soft headboard invites you in for a good night sleep.',
                'dimension_id' =>    52,
                'quantity' => 5,
                'sale_amount' => 35,
                'created_at' => $this->faker->dateTimeBetween('2010-01-01'),
            ],
            [
                'product_name' =>    'HOUSTON UPHOLSTERED BED WITH STORAGE',
                'category_id' =>    6,
                'price' =>    64330000,
                'brand_id' =>    2,
                'description' =>    'Relax and enjoy the comfort of Houston. The soft headboard with elegant design details ensures a welcoming look to your bed and great support whether sitting up or lounging with a book.',
                'dimension_id' =>    53,
                'quantity' => 3,
                'sale_amount' => 85,
                'created_at' => $this->faker->dateTimeBetween('2010-01-01'),
            ],
            [
                'product_name' =>    'LUGANO STORAGE BED WITH LIFT-UP FRAME AND SLATS',
                'category_id' =>    6,
                'price' =>    45490000,
                'brand_id' =>    4,
                'description' =>    'Let your body sink down and feel relaxation wash over you. Sleep like an angel in the elegant Lugano bed. Keeping a minimalist look with a clean wooden frame, this modern bed will bring a sense of calm and serenity to your bedroom. Fitted with a plinth base for a more masculine, heavy look this bed invites you into comfort.',
                'dimension_id' =>    54,
                'quantity' => 4,
                'sale_amount' => 53,
                'created_at' => $this->faker->dateTimeBetween('2010-01-01'),
            ],
            [
                'product_name' =>    'MEZZO BED EXCL MATTRESS',
                'category_id' =>    6,
                'price' =>    38500000,
                'brand_id' =>    1,
                'description' =>    'Defined by grandiose lines and an elegant look, this modern bed will transform any ordinary bedroom into a luxurious sanctuary. The Mezzo is the Rolls Royce of beds and we guarantee it will bring you safely to dreamland.',
                'dimension_id' =>    55,
                'quantity' => 5,
                'sale_amount' => 52,
                'created_at' => $this->faker->dateTimeBetween('2010-01-01'),
            ],
            [
                'product_name' =>    'LUGANO BED EXCL MATTRESS',
                'category_id' =>    6,
                'price' =>    21990000,
                'brand_id' =>    2,
                'description' =>    'Let your body sink down and feel relaxation wash over you. Sleep like an angel in the elegant Lugano bed. Keeping a minimalist look with a clean wooden frame, this modern bed will bring a sense of calm and serenity to your bedroom. Fitted with a plinth base for a more masculine, heavy look this bed invites you into comfort.',
                'dimension_id' =>    56,
                'quantity' => 5,
                'sale_amount' => 2,
                'created_at' => $this->faker->dateTimeBetween('2010-01-01'),
            ],
            [
                'product_name' =>    'LUGANO WITHOUT HEADBOARD WITH SLATS AND LEGS',
                'category_id' =>    6,
                'price' =>    29590000,
                'brand_id' =>    1,
                'description' =>    'Defined by grandiose lines and an elegant look, this modern bed will transform any ordinary bedroom into a luxurious sanctuary. The Mezzo is the Rolls Royce of beds and we guarantee it will bring you safely to dreamland.',
                'dimension_id' =>    57,
                'quantity' => 5,
                'sale_amount' => 3,
                'created_at' => $this->faker->dateTimeBetween('2010-01-01'),
            ],
            [
                'product_name' =>    'LUGANO STORAGE BED WITH LIFTUP FRAME AND SLATS EXCL MATTRESS',
                'category_id' =>    6,
                'price' =>    29190000,
                'brand_id' =>    3,
                'description' =>    'Let your body sink down and feel relaxation wash over you. Sleep like an angel in the elegant Lugano bed. Keeping a minimalist look with a clean wooden frame, this modern bed will bring a sense of calm and serenity to your bedroom. Fitted with a plinth base for a more masculine, heavy look this bed invites you into comfort.',
                'dimension_id' =>    58,
                'quantity' => 5,
                'sale_amount' => 35,
                'created_at' => $this->faker->dateTimeBetween('2010-01-01'),
            ],
            [
                'product_name' =>    'HOUSTON BED EXCL MATTRESS',
                'category_id' =>    6,
                'price' =>    39060000,
                'brand_id' =>    5,
                'description' =>    'Relax and enjoy the comfort of Houston. The soft headboard with elegant design details ensures a welcoming look to your bed and great support whether sitting up or lounging with a book.',
                'dimension_id' =>    59,
                'quantity' => 1,
                'sale_amount' => 4,
                'created_at' => $this->faker->dateTimeBetween('2010-01-01'),
            ],
            [
                'product_name' =>    'MEZZO STORAGE BED WITH LIFTUP FRAME AND SLATS EXCL MATTRESS',
                'category_id' =>    6,
                'price' =>    47270000,
                'brand_id' =>    5,
                'description' =>    'Defined by grandiose lines and an elegant look, this modern bed will transform any ordinary bedroom into a luxurious sanctuary. The Mezzo is the Rolls Royce of beds and we guarantee it will bring you safely to dreamland. Lift the bed frame and reveal plenty of storage space for extra bedding, thick winter blankets or perhaps even for hiding presents.',
                'dimension_id' =>    60,
                'quantity' => 3,
                'sale_amount' => 6,
                'created_at' => $this->faker->dateTimeBetween('2010-01-01'),
            ],
            [
                'product_name' =>    'KUTA FLOOR LAMP',
                'category_id' =>    7,
                'price' =>    14290000,
                'brand_id' =>    1,
                'description' =>    'The Kuta floor lamp has a simple and stylish design. The dominant round shade and the long reach make it the perfect piece to couple with your sofa or dining table. Available in different colours, The Kuta floor lamp is sure to light up your interior.',
                'dimension_id' =>    61,
                'quantity' => 9,
                'sale_amount' => 7,
                'created_at' => $this->faker->dateTimeBetween('2010-01-01'),
            ],
            [
                'product_name' =>    'PINE CONE PENDANT',
                'category_id' =>    7,
                'price' =>    18990000,
                'brand_id' =>    4,
                'description' =>    'Designers Charlotte Høncke and Olaf Recht, went into nature for their inspiration to the Pine cone lamp. The round shapes and multiple layers combine with the beautiful finish to give the lamp a warm and soft light. Hang several Pine Cone pendants together for an artistic, contemporary expression.',
                'dimension_id' =>    62,
                'quantity' => 10,
                'sale_amount' => 7,
                'created_at' => $this->faker->dateTimeBetween('2010-01-01'),
            ],
            [
                'product_name' =>    'DAWN TABLE LAMP',
                'category_id' =>    7,
                'price' =>    14290000,
                'brand_id' =>    3,
                'description' =>    'The Kuta floor lamp has a simple and stylish design. The dominant round shade and the long reach make it the perfect piece to couple with your sofa or dining table.',
                'dimension_id' =>    63,
                'quantity' => 9,
                'sale_amount' => 6,
                'created_at' => $this->faker->dateTimeBetween('2010-01-01'),
            ],
            [
                'product_name' =>    'QUADRO WALL LAMP',
                'category_id' =>    7,
                'price' =>    11490000,
                'brand_id' =>    3,
                'description' =>    'Get inspired by a simple, Scandinavian design. The Quadro lamp has a minimalistic look and quadratic lines. The black wall lamp with an adjustable LED light is the perfect match for bedsides and reading spots.',
                'dimension_id' =>    64,
                'quantity' => 4,
                'sale_amount' => 47,
                'created_at' => $this->faker->dateTimeBetween('2010-01-01'),
            ],
            [
                'product_name' =>    'SHELTER TABLE LAMP',
                'category_id' =>    7,
                'price' =>    22490000,
                'brand_id' =>    4,
                'description' =>    'With the sculptural design and the dominant shade, the Shelter table lamp could be the perfect eye-catcher in your home. The combination of black metal with a brass arm is very trendy and ensures a modern expression to the iconic design.',
                'dimension_id' =>    65,
                'quantity' => 5,
                'sale_amount' => 0,
                'created_at' => $this->faker->dateTimeBetween('2010-01-01'),
            ],
            [
                'product_name' =>    'LEVEL PENDANT',
                'category_id' =>    7,
                'price' =>    21190000,
                'brand_id' =>    4,
                'description' =>    'With the sculptural design and the dominant shade, the Shelter table lamp could be the perfect eye-catcher in your home. The combination of black metal with a brass arm is very trendy and ensures a modern expression to the iconic design.',
                'dimension_id' =>    66,
                'quantity' => 2,
                'sale_amount' => 10,
                'created_at' => $this->faker->dateTimeBetween('2010-01-01'),
            ],
            [
                'product_name' =>    'FIVE CHANDELIER',
                'category_id' =>    7,
                'price' =>    8990000,
                'brand_id' =>    6,
                'description' =>    'The Five pendant is the BoConcept Design Team’s take on the modern chandelier. Combining the very trendy antique brass with elegant arms that leaves the light bulb exposed, the Five lamp gives a dynamic and contemporary expression to your home.',
                'dimension_id' =>    67,
                'quantity' => 8,
                'sale_amount' => 4,
                'created_at' => $this->faker->dateTimeBetween('2010-01-01'),
            ],
            [
                'product_name' =>    'CURIOUS FLOOR LAMP',
                'category_id' =>    7,
                'price' =>    13490000,
                'brand_id' =>    1,
                'description' =>    'The Kuta floor lamp has a simple and stylish design. The dominant round shade and the long reach make it the perfect piece to couple with your sofa or dining table.',
                'dimension_id' =>    68,
                'quantity' => 9,
                'sale_amount' => 7,
                'created_at' => $this->faker->dateTimeBetween('2010-01-01'),
            ],
            [
                'product_name' =>    'DEMAND TABLE LAMP',
                'category_id' =>    7,
                'price' =>    13490000,
                'brand_id' =>    2,
                'description' =>    'Do you demand an aesthetic and pleasing design? Or do you demand a functional lamp for your current needs? The Demand lamp will do it all for you.',
                'dimension_id' =>    69,
                'quantity' => 5,
                'sale_amount' => 5,
                'created_at' => $this->faker->dateTimeBetween('2010-01-01'),
            ],
            [
                'product_name' =>    'STOCKHOLM TABLE LAMP',
                'category_id' =>    7,
                'price' =>    21890000,
                'brand_id' =>    2,
                'description' =>    'The Stockholm lamp combines colored glass with a solid marble base for a simple and minimalistic design. The Stockholm lamp is the perfect way to add a decorative item in mixed materials to your home decor.',
                'dimension_id' =>    70,
                'quantity' => 5,
                'sale_amount' => 8,
                'created_at' => $this->faker->dateTimeBetween('2010-01-01'),
            ],

        ]);
    }
}
